apiVersion: v2
name: testbed
description: A Helm chart for testing Helm and Kubernetes concepts
type: application
# Chart version
version: '0.30.0'
# Application version
appVersion: '0.30.0'
home: https://github.com/juanjjaramillo/testbed/blob/main/charts/testbed/README.md
sources:
  - https://github.com/juanjjaramillo/testbed/
maintainers:
  - name: Juan Jose Jaramillo
    url: https://github.com/juanjjaramillo
icon: https://raw.githubusercontent.com/juanjjaramillo/testbed/main/misc/logo.svg
